In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

tf.__version__

'2.1.0'

In [2]:
path_to_file = 'shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


The RNN Character will actually learn the structure of the text from William Shakespeare

In [5]:
path_to_file = 'shakespeare.txt'

In [6]:
vocab = sorted(set(text))

In [7]:
len(vocab)

84

In [8]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [9]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind['H']

33

In [11]:
ind_to_char = np.array(vocab)

In [12]:
ind_to_char[55]

'`'

In [13]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [14]:
encoded_text.shape

(5445609,)

In [15]:
sample = text[:500]

In [16]:
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [17]:
print(sample)


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [18]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [19]:
line = "From fairest creatures we desire increase"
len(line)

41

In [20]:
# 3 lines to understand structure
lines = '''
From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  '''
len(lines)

135

In [21]:
seq_len = 135

In [22]:
total_num_seq = len(text) // (seq_len+1)

In [23]:
total_num_seq

40041

In [24]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [25]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
# for item in char_dataset.take(500):
#     print(ind_to_char[item.numpy()])

In [27]:
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [28]:
def create_seq_targets(seq):
    input_txt = seq[:-1] #Hello my nam
    target_txt = seq[1:] #ello my name
    return input_txt, target_txt

In [29]:
dataset = sequences.map(create_seq_targets)

In [30]:
for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75
  1 56 74  1 75 63 60  1 73 64 71 60 73  1 74]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper s


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1
 56 74  1 75 63 60  1 73 64 71 60 73  1 74 63]
                     1
  From fairest 

In [31]:
batch_size = 128

buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [32]:
dataset

<BatchDataset shapes: ((128, 135), (128, 135)), types: (tf.int32, tf.int32)>

In [33]:
# Creating the model

In [34]:
vocab_size = len(vocab)
vocab_size

84

In [35]:
embed_dim = 64

In [36]:
rnn_neurons = 1026

In [37]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [38]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [39]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GRU, Dense, LSTM

In [40]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim, batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons, return_sequences=True,
                 stateful=True, recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    
    return model

In [41]:
model = create_model(vocab_size=vocab_size,
                    embed_dim=embed_dim,
                    rnn_neurons = rnn_neurons,
                    batch_size = batch_size)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [42]:
# Training the model

In [43]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)

In [44]:
# probabilities of each character
example_batch_predictions[0]

<tf.Tensor: shape=(135, 84), dtype=float32, numpy=
array([[ 5.7929032e-04, -2.2664322e-03,  4.6816729e-03, ...,
        -2.9412957e-03, -7.3828886e-04, -8.1398450e-03],
       [-2.0599971e-03, -7.4405894e-03,  9.8912120e-03, ...,
        -2.8964311e-03,  2.9725330e-03, -4.4526919e-03],
       [-2.3784360e-04, -1.0696603e-03,  1.1600534e-02, ...,
        -2.5966740e-03, -5.6503941e-03, -4.8050075e-05],
       ...,
       [-5.6173243e-03, -2.9784967e-03,  5.4900460e-03, ...,
        -1.0963663e-03, -3.9545069e-03,  2.8088181e-03],
       [-4.8153857e-03, -8.7872045e-03,  1.0076446e-02, ...,
        -1.6786165e-03,  1.0298826e-03,  2.0040581e-03],
       [-1.6217739e-03, -2.0678081e-03,  1.1527120e-02, ...,
        -1.7190730e-03, -6.9997516e-03,  3.5737138e-03]], dtype=float32)>

In [45]:
samples_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [46]:
# samples_indices

In [47]:
samples_indices = tf.squeeze(samples_indices, axis=-1).numpy()

In [48]:
samples_indices

array([21, 53, 49, 43, 43,  8, 54, 47, 74,  1, 83, 25,  7,  4, 58, 40, 44,
       64, 56, 27, 79, 32, 61, 40, 41, 39, 14, 77,  8,  7, 41, 68, 70, 62,
       44, 62, 52, 82, 78, 39, 31, 15, 82, 71, 51, 60, 36, 14,  9, 45, 26,
        8, 60, 53, 45, 33, 41, 19, 21, 16, 57, 79, 46, 46, 59, 24, 35, 66,
       78, 56, 36, 79, 10, 79, 75, 46, 51, 45,  5,  8, 71, 45, 54, 57, 12,
       45, 47, 27,  1, 28,  8, 34, 73, 66, 37, 18, 81, 73, 66, 81, 28, 37,
        6, 61, 14, 14, 63, 12,  9, 36, 10, 31,  0, 46, 23, 55, 50, 50, 79,
       20, 28, 23, 77, 39, 19, 82, 81, 26, 13,  6, 43, 39, 39, 49,  3],
      dtype=int64)

In [49]:
ind_to_char[samples_indices]

array([':', ']', 'X', 'R', 'R', ',', '_', 'V', 's', ' ', '}', '?', ')',
       '&', 'c', 'O', 'S', 'i', 'a', 'B', 'x', 'G', 'f', 'O', 'P', 'N',
       '3', 'v', ',', ')', 'P', 'm', 'o', 'g', 'S', 'g', '[', '|', 'w',
       'N', 'F', '4', '|', 'p', 'Z', 'e', 'K', '3', '-', 'T', 'A', ',',
       'e', ']', 'T', 'H', 'P', '8', ':', '5', 'b', 'x', 'U', 'U', 'd',
       '>', 'J', 'k', 'w', 'a', 'K', 'x', '.', 'x', 't', 'U', 'Z', 'T',
       "'", ',', 'p', 'T', '_', 'b', '1', 'T', 'V', 'B', ' ', 'C', ',',
       'I', 'r', 'k', 'L', '7', 'z', 'r', 'k', 'z', 'C', 'L', '(', 'f',
       '3', '3', 'h', '1', '-', 'K', '.', 'F', '\n', 'U', '<', '`', 'Y',
       'Y', 'x', '9', 'C', '<', 'v', 'N', '8', '|', 'z', 'A', '2', '(',
       'R', 'N', 'N', 'X', '"'], dtype='<U1')

In [50]:
epochs = 40
model.fit(dataset, epochs=epochs)

Train for 312 steps
Epoch 1/40
312/312 [==============================] - 53s 168ms/step - loss: 2.6194
Epoch 2/40
312/312 [==============================] - 52s 166ms/step - loss: 1.8566
Epoch 3/40
312/312 [==============================] - 52s 166ms/step - loss: 1.5596
Epoch 4/40
312/312 [==============================] - 52s 166ms/step - loss: 1.4019
Epoch 5/40
312/312 [==============================] - 52s 167ms/step - loss: 1.3191
Epoch 6/40
312/312 [==============================] - 52s 167ms/step - loss: 1.2679
Epoch 7/40
312/312 [==============================] - 52s 168ms/step - loss: 1.2325
Epoch 8/40
312/312 [==============================] - 52s 165ms/step - loss: 1.2051
Epoch 9/40
312/312 [==============================] - 52s 167ms/step - loss: 1.1828
Epoch 10/40
312/312 [==============================] - 53s 169ms/step - loss: 1.1638
Epoch 11/40
312/312 [==============================] - 52s 168ms/step - loss: 1.1471
Epoch 12/40
312/312 [==============================] -

In [53]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

from tensorflow.keras.models import load_model
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1, None]))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_1 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [54]:
# take in a mode, start_seed, gensize, and temp
# take the string, put it in index location, format and put in model, reset the model

def generate_text(model, start_seed, gen_size=500, temp=0.1):
    num_generate = gen_size
    input_eval = [char_to_ind[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval,0)
    text_generated = []
    temperature = temp
    model.reset_states()
    
# for each of the characters, we will get a prediction, squeeze to undo the dimension and grab them,
# What is the probability for each character, 
# get a single index digit as numpy, then start appending the text - join all together
    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions, 0)
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        input_eval = tf.expand_dims([predicted_id], 0)
        text_generated.append(ind_to_char[predicted_id])
        
    return (start_seed+"".join(text_generated))

In [55]:
print(generate_text(model, "JULIET", gen_size=1000))

JULIETHET. And I will with your honour and your son,
    The which he loves me well; and that is mine
    When I shall see thee here in passion with thee.
    I say the truth is stol'n away the fool,
    And that the noble Marcus Diomed,
    And with the hand of mine hath sent to you
    Where they shall have a sport in this world cannot be thus complete me
    To be a sign of love and love and war.
  PETRUCHIO. Why, this is here at hand, I say.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [56]:
tf.test.gpu_device_name()

'/device:GPU:0'